Repository CS2103-AY1819S1-F10-1/main, pull requests merged in 2018-11, with the labels that each got.

#174 Archive, Restore features
  docs/team/joshuarobert.adoc
  src/main/java/seedu/address/commons/events/ui/ArchiveListEvent.java
  src/main/java/seedu/address/commons/events/ui/JumpToListRequestEvent.java
  src/main/java/seedu/address/logic/commands/ArchiveCommand.java
  src/main/java/seedu/address/logic/commands/AutoCompleteCommandHelper.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/RestoreCommand.java
  src/main/java/seedu/address/logic/commands/SelectCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/RestoreCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/permission/Permission.java
  src/main/java/seedu/address/model/permission/PermissionSet.java
  src/main/java/seedu/address/ui/ListPicker.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/ui/AssignmentListPanelTest.java
  src/test/java/seedu/address/ui/PersonListPanelTest.java
  src/test/java/systemtests/EditCommandSystemTest.java
  src/test/java/systemtests/FindCommandSystemTest.java
Labels: priority.High, status.Ongoing

#178 Update features
  src/main/java/seedu/address/commons/events/ui/ChangeOnListPickerClickEvent.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/ListPicker.java
  src/test/java/seedu/address/logic/commands/AddAssignmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High, status.Ongoing

#180 Comment disable button
  src/main/java/seedu/address/ui/ListPicker.java
Labels: priority.Low

#182 Update select in Archive
  src/main/java/seedu/address/logic/commands/SelectCommand.java
Labels: priority.High, type.Story

#140 Created Portfolio File
  docs/DeveloperGuide.adoc
  docs/team/raynard.adoc
Labels: status.Ongoing
